# 支持阿里云 https证书申请，还未测试
# 
# 
# run:
# docker volume create caddy_data
# vi Caddyfile #config Caddyfile
# docker compose up -d

# Caddyfile example:
# 
# www.example.com {
#   reverse_proxy 192.168.99.123:5001

#   tls {
#     dns lego_deprecated alidns
#   }
# }

version: "3.7"

services:
  caddy:
    image: theelves/caddy-lego:latest
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    # cap_add:
    #   - NET_ADMIN
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config: