# run:
# docker volume create caddy_data
# vi Caddyfile #config Caddyfile
# docker compose up -d

version: "3.7"

services:
  caddy:
    # image: caddy:latest
    image: theelves/caddy-lego:latest
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config: