#linux环境
#git地址：https://github.com/v2rayA/v2rayA
#官方文档：https://v2raya.org/docs/prologue/installation/docker/

version: '3.8'
services:
  v2raya:
    image: mzz2017/v2raya
    container_name: v2raya
    privileged: true
    network_mode: host
    restart: always
    environment:
      - V2RAYA_LOG_FILE=/tmp/v2raya.log
      - V2RAYA_V2RAY_BIN=/usr/local/bin/xray
      # - V2RAYA_V2RAY_BIN=/usr/local/bin/v2ray #传统v2ray，不支持vless reality
      - V2RAYA_NFTABLES_SUPPORT=off
      - IPTABLES_MODE=legacy
    volumes:
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/v2raya:/etc/v2raya
