version: "3"

services:
  3x-ui:
    # image: ghcr.io/mhsanaei/3x-ui:latest
    # image: lovechen/3x-ui
    image: enkidu6/3x-ui
    container_name: 3x-ui
    hostname: yourhostname
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped
