version: '3.8'

services:
  wg:
    image: place1/wg-access-server
    container_name: wg
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /opt/wg:/data
    environment:
      WG_ADMIN_PASSWORD: "${WG_ADMIN_PASSWORD}"
      WG_WIREGUARD_PRIVATE_KEY: "${WG_WIREGUARD_PRIVATE_KEY}"
    ports:
      - "18000:8000/tcp"
      - "11820:51820/udp"
    restart: unless-stopped

#官网地址：https://github.com/Place1/wg-access-server
#等效命令：
# docker run   --name wg   -d   --cap-add NET_ADMIN   --device /dev/net/tun:/dev/net/tun   -v /opt/wg:/data   -e "WG_ADMIN_PASSWORD=$WG_ADMIN_PASSWORD"   -e "WG_WIREGUARD_PRIVATE_KEY=$WG_WIREGUARD_PRIVATE_KEY"   -p 18000:8000/tcp   -p 11820:51820/udp   place1/wg-access-server