version: '3.8'

services:
  ftps-server:
    container_name: ftps-server  # 设置容器名
    image: ftps-server  # 设置镜像名
    build: .
    ports:
      - "10012:10012"
      - "10000-10010:10000-10010"
    environment:
      FTP_USER: ${FTP_USER:-ftpsuser}
      FTP_PASS: ${FTP_PASS:-ftpsuser}
      PASV_IP: ${PASV_IP:-127.0.0.1} # 设置被动模式的IP地址, 一般设置为宿主机的IP地址，否则可能会出现无法连接的问题
      FTP_PORT: ${FTP_PORT:-10012}
      PASV_MIN_PORT: ${PASV_MIN_PORT:-10000} # 设置被动模式的端口范围最小值，要和端口映射的范围一致
      PASV_MAX_PORT: ${PASV_MAX_PORT:-10010} # 设置被动模式的端口范围最大值，要和端口映射的范围一致
    volumes:
      - ./ftp_cfg/:/etc/vsftpd/
      - ./ftp_data:/home/
    restart: always
