version: '3.8'

services:
  sub-web-modify:
    image: youshandefeiyang/sub-web-modify
    container_name: sub-web-modify
    restart: unless-stopped
    privileged: true
    ports:
      - "58080:80"