name: OpenCV CUDA Docker Image Build and Push

on:
  workflow_dispatch:
    inputs:
      NVIDIA_CUDA_VERSION:
        description: 'NVIDIA CUDA Version'
        required: false
        default: '11.1.1'
      OPENCV_VERSION:
        description: 'OpenCV Version'
        required: false
        default: '4.7.0'
      AI_PY_VERSION:
        description: 'Python Version for AI'
        required: false
        default: '3.8'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Free Disk Space
      run: bash ./tools/free_disk_space.sh
        
    - name: Print system information
      run: |
        echo "Operating System:"
        uname -a
        echo "CPU details:"
        lscpu
        echo "Memory details:"
        free -h
        echo "Disk details:"
        df -h
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./DEV/opencv
        file: ./DEV/opencv/dockerfile-opencv-cuda
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/opencv-cuda:cv_${{ github.event.inputs.OPENCV_VERSION}}_cuda_${{ github.event.inputs.NVIDIA_CUDA_VERSION}},

        build-args: |
          NVIDIA_CUDA_VERSION=${{ github.event.inputs.NVIDIA_CUDA_VERSION }}
          OPENCV_VERSION=${{ github.event.inputs.OPENCV_VERSION }}
          AI_PY_VERSION=${{ github.event.inputs.AI_PY_VERSION }}

    - name: Print Disk information
      run: |
        echo "Disk details:"
        df -h
        echo "Docker images:"
        docker images
