name: Stable Diffusion WebUI Docker Image Build and Push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Print system information
      run: |
        echo "Operating System:"
        uname -a
        echo "CPU details:"
        lscpu
        echo "Memory details:"
        free -h
        echo "Disk details:"
        df -h

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Get Current Timestamp
      id: current-time
      run: echo "TIMESTAMP=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV
    
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./stable-diffusion-webui
        file: ./stable-diffusion-webui/dockerfile-sd-webui
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/stable-difusion-webui:${{ env.TIMESTAMP }}
