name: Stable Diffusion WebUI Docker Image Build and Push

on:
  workflow_dispatch:
    inputs:
      NVIDIA_CUDA_VERSION:
        description: 'NVIDIA CUDA Version'
        required: false
        default: '12.1.1'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Free Disk Space
      run: bash ./tools/free_disk_space.sh
        
    - name: Print system information
      run: |
        echo "Operating System:"
        uname -a
        echo "CPU details:"
        lscpu
        echo "Memory details:"
        free -h
        echo "Disk details:"
        df -h

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Get Current Timestamp
      id: current-time
      run: echo "TIMESTAMP=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV
    
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./AI/stable-diffusion-webui
        file: ./AI/stable-diffusion-webui/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/stable-difusion-webui:cuda_${{ github.event.inputs.NVIDIA_CUDA_VERSION}}_${{ env.TIMESTAMP }},
          ${{ secrets.DOCKERHUB_USERNAME }}/stable-difusion-webui:latest
        build-args: |
          NVIDIA_CUDA_VERSION=${{ github.event.inputs.NVIDIA_CUDA_VERSION }}

    - name: Print Disk information
      run: |
        echo "Disk details:"
        df -h
        echo "Docker images:"
        docker images
